# Generated by Django 5.0.6 on 2024-05-12 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_last_viewed_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_viewed_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 23, 50, 30, 667442)),
        ),
    ]
